name: 'Setup environment for the build'

inputs:
    cache-disabled:
        description: 'gradle.cache-disabled'
        default: 'false'
    cache-read-only:
        description: 'gradle.cache-read-only'
        default: 'false'
    java-version:
        description: 'Java version'
        default: '21'

env:
    GRADLE_OPTS: "--no-daemon -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

runs:
    using: 'composite'
    steps:
        -   name: Configure JDK
            uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 #v4.7.1
            with:
                distribution: 'zulu'
                java-version: ${{ inputs.java-version }}

        -   uses: gradle/actions/setup-gradle@06832c7b30a0129d7fb559bcc6e43d26f6374244 #v4.3.1
            with:
                validate-wrappers: true
                cache-disabled: ${{ inputs.cache-disabled }}
                cache-read-only: ${{ inputs.cache-read-only }}

        -   name: Cache Gradle Wrapper
            uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 #v4.2.3
            id: gradle-wrapper-cache
            with:
                path: ~/.gradle/wrapper
                key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
                restore-keys: ${{ runner.os }}-gradle-wrapper-
                enableCrossOsArchive: true

        -   name: Cache Node Modules
            uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 #v4.2.3
            id: gradle-yarn-cache
            with:
                path: build/js/node_modules
                key: ${{ runner.os }}-yarn-${{ hashFiles('gradle/js/yarn.lock') }}
                restore-keys: ${{ runner.os }}-yarn-
                enableCrossOsArchive: true

        -   name: Initialize Gradle wrapper
            if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
            run: chmod +x ./gradlew
            shell: "bash"

        -   name: Cache Konan
            uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 #v4.2.3
            with:
                path: |
                    ~/.konan/cache
                    ~/.konan/dependencies
                    ~/.konan/kotlin-native-macos*
                    ~/.konan/kotlin-native-mingw*
                    ~/.konan/kotlin-native-windows*
                    ~/.konan/kotlin-native-linux*
                    ~/.konan/kotlin-native-prebuilt-macos*
                    ~/.konan/kotlin-native-prebuilt-mingw*
                    ~/.konan/kotlin-native-prebuilt-windows*
                    ~/.konan/kotlin-native-prebuilt-linux*
                key: ${{ runner.os }}-konan-${{ hashFiles('**/*.gradle*') }}
                restore-keys: |
                    ${{ runner.os }}-konan-

        -   if: matrix.os == 'Windows'
            uses: msys2/setup-msys2@61f9e5e925871ba6c9e3e8da24ede83ea27fa91f #v2.27.0
            with:
                release: false
                install: mingw-w64-x86_64-openssl
