name: Run build KMP for JVM

on:
    workflow_dispatch:
    workflow_call:

defaults:
    run:
        shell: bash

permissions:
    contents: read

env:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
    build-jvm:
        name: Run build on ${{ matrix.os }}

        continue-on-error: false
        strategy:
            fail-fast: true
            matrix:
                os: [ 'ubuntu-latest' ]

        runs-on: ${{ matrix.os }}
        timeout-minutes: 15

        concurrency:
            group: run-build-${{ github.workflow }}-${{ github.ref }}-${{ matrix.os }}
            cancel-in-progress: true

        steps:
            -   name: Checkout
                uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

            -   name: Setup environment
                uses: ./.github/actions/setup
                with:
                    cache-read-only: ${{ github.ref != 'refs/heads/main' }}

            -   name: Run check
                continue-on-error: false
                run: |
                    ./gradlew -s detekt check

            -   name: (Fail-only) Upload reports
                if: failure()
                uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
                with:
                    name: reports-build-jvm
                    path: |
                        **/build/reports/**
