name: Cleanup caches

on:
    workflow_dispatch:

jobs:
    cleanup:
        runs-on: ubuntu-latest
        steps:
            -   name: Cleanup
                run: |
                    echo "Fetching list of cache key"
                    cacheKeys=$(gh cache list --json id --jq '.[].id')

                    ## Setting this to not fail the workflow while deleting cache keys.
                    set +e
                    echo "Deleting caches..."
                    for cacheKey in $cacheKeys
                    do
                        gh cache delete $cacheKey
                    done
                    echo "Done"
                env:
                    GH_TOKEN: ${{ github.token }}
