name: CI Branch

on:
    workflow_dispatch:
    push:
        branches-ignore:
            - main
        paths-ignore:
            - "**.md"
            - ".idea/**"
            - ".editorconfig"
            - ".gitattributes"
            - ".gitignore"

permissions:
    contents: read

concurrency:
    group: ci-branch-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    commit-messages-validation:
        uses: ./.github/actions/commit-messages-validation/action.yml

    build:
        uses: ./.github/workflows/run-build.yml
