name: CI Main

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths-ignore:
            - "**.md"
            - ".idea/**"
            - ".editorconfig"
            - ".gitattributes"
            - ".gitignore"

permissions:
    contents: read

concurrency:
    group: ci-main-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        uses: ./.github/workflows/run-build.yml
