name: CI Pull Request

on:
    pull_request:
        types:
            - reopened
            - synchronize
            - opened
            - ready_for_review
        branches:
            - main
        paths-ignore:
            - "**.md"
            - ".idea/**"
            - ".editorconfig"
            - ".gitattributes"
            - ".gitignore"

permissions:
    contents: read

concurrency:
    group: ci-pr-${{ github.workflow }}-${{ github.event.ref }}-${{ github.event.pull_request.id }}"
    cancel-in-progress: true

jobs:
    checks:
        uses: ./.github/workflows/run-build.yml

    codeql:
        uses: ./.github/workflows/run-codeql.yml
        secrets: inherit
