name: CI Publish

on:
    release:
        types:
            - released
            - prereleased

permissions:
    contents: read

concurrency:
    group: ci-publish-${{ github.workflow }}-${{ github.event.ref }}
    cancel-in-progress: true

jobs:
    publish:
        uses: ./.github/workflows/run-publish.yml
        secrets: inherit
