name: CI Release

on:
    push:
        tags:
            - '*'

concurrency:
    group: ci-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    checks:
        uses: ./.github/workflows/run-checks.yml
