name: CI Release

on:
    release:
        types:
            - published

concurrency:
    group: ci-release-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    release:
        uses: ./.github/workflows/run-release.yml
