name: 'Stale Pull Requests'

on:
    workflow_dispatch:

permissions:
    issues: none
    pull-requests: write

jobs:
    weekly:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/stale@5bef64f19d7facfb25b37b414482c7164d639639 #v9.1.0
              id: stale
              with:
                  stale-pr-message: 'This pull request has been open and inactive. It will be closed shortly.'
                  days-before-stale: 60
                  days-before-close: 7
                  exempt-draft-pr: true
                  exempt-pr-labels: 'WIP'
            - name: Print outputs
              run: echo ${{ join(steps.stale.outputs.*, ',') }}
