name: Run publish

on:
    workflow_call:

defaults:
    run:
        shell: bash

permissions:
    contents: read

env:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
    run-publish:
        continue-on-error: false
        strategy:
            fail-fast: true
            matrix:
                os: [ 'ubuntu-latest' ]

        runs-on: ${{ matrix.os }}
        name: Publish to Maven Central

        concurrency:
            group: run-publish-${{ github.workflow }}-${{ github.ref }}-${{ matrix.os }}
            cancel-in-progress: true

        steps:
            -   name: Checkout code
                uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

            -   name: Setup environment
                uses: ./.github/actions/setup
                with:
                    cache-read-only: ${{ github.ref_name != 'main' }}

            -   name: Publish to Maven Central
                env:
                    GPG_SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
                    GPG_SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
                    GPG_SIGNING_PASSPHRASE: ${{ secrets.SIGNING_KEY_PASSWORD }}
                    ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
                    ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
                run: |
                    VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3 | sed 's/^v//')
                    echo "New version: ${VERSION}"

                    ./gradlew --no-configuration-cache -Pversion=${VERSION} publishToMavenCentral
